<%@ page import="org.apache.commons.lang.StringUtils"%>
    <%@ page import="org.jahia.params.valves.LogoutConfig"%>
    <%@ page import="org.jahia.bin.Logout"%><%@ page import="java.net.URLEncoder"%>
    <%@ page language="java" contentType="text/javascript" %>
    <%-- Read logout url as done in org.jahia.services.render.URLGenerator.getLogout() --%>
    <%
    String redirect = "redirect=" + request.getContextPath() + "/start";
    String customLogoutUrl = LogoutConfig.getInstance().getCustomLogoutUrl(request);
    String logoutUrl;

    // QA-14763: DIRTY hack here to determine if we have a custom logout URL generated by CAS or not to have a correct redirection ...
    if (StringUtils.isNotEmpty(customLogoutUrl)) {
        if (customLogoutUrl.contains("?service=")) {
            // CAS generated custom URL is like:
            // https://******/cas/logout?service=http%3A%2F%2Flocalhost%3A8080%2Fcms%2Flogout
            // So we need to add the redirect param encoded at the end.
            logoutUrl = customLogoutUrl + URLEncoder.encode("?" + redirect, "UTF-8");
        } else if (customLogoutUrl.contains("?")){
            // custom url already contain queryString, append redirect param
            logoutUrl = customLogoutUrl + "&" + redirect;
        } else {
            // custom url doesn't contain queryString, build one.
            logoutUrl = customLogoutUrl + "?" + redirect;
        }
    } else {
        logoutUrl = request.getContextPath() + Logout.getLogoutServletPath() + "?" + redirect;
    }
    %>
    contextJsParameters.config.logoutUrl = "<%=logoutUrl%>";

